        endString DB 0dh, 0ah

DB 0dh, 0ah
DB 0dh, 0ah
DB 0dh, 0ah
DB 0dh, 0ah
DB 0dh, 0ah
DB "    .d8888b.  888888b.          .d8888b."
DB 0dh, 0ah
DB "   d88P  Y88b 888  `88b        d88P  Y88b   [Programmed by Andrew Ferrier]"
DB 0dh, 0ah
DB "   Y88b.      888  .88P        Y88b."
DB 0dh, 0ah
DB "    `Y888b.   8888888K.         `Y888b.    .d8888b .d88b.  88888b.   .d88b."
DB 0dh, 0ah
DB "       `Y88b. 888  `Y88b           `Y88b. d88P'   d88'`88b 888 `88b d8P  Y8b"
DB 0dh, 0ah
DB "         `888 888    888 888888      `888 888     888  888 888  888 88888888"
DB 0dh, 0ah
DB "   Y88b  d88P 888   d88P       Y88b  d88P Y88b.   Y88..88P 888 d88P Y8b."
DB 0dh, 0ah
DB "    `Y8888P'  8888888P'         `Y8888P'   `Y8888P `Y88P'  88888P'   `Y8888"
DB 0dh, 0ah
DB "                                                           888"
DB 0dh, 0ah
DB "                 version 0.97                              888"
DB 0dh, 0ah
DB "                                                           888"
DB 0dh, 0ah
DB 0dh, 0ah
DB 0dh, 0ah
DB "                    __                     __     _"
DB 0dh, 0ah
DB "            |_     (_ ._ |_  _ ._ _ o _|  (_  _ _|_ _|_     _.._ _"
DB 0dh, 0ah
DB "            |_)\/  __)|_)| |(/_| (_)|(_|  __)(_) |   |_\/\/(_|| (/_"
DB 0dh, 0ah
DB "               /      |"
DB 0dh, 0ah
DB 0dh, 0ah
DB 0dh, 0ah
DB 0dh, 0ah
DB 0dh, 0ah
DB 0dh, 0ah
DB 0dh, 0ah
DB "               Written in pure, optimised 386+ assembly language."
DB 0dh, 0ah
DB 0dh, 0ah
DB "                            This program is freeware."
DB 0dh, 0ah
DB 0dh, 0ah
DB "   See SBSCOPE.TXT for more information on SB-Scope, and Spheroid Software."
DB 0dh, 0ah
DB 0dh, 0ah
DB 0dh, 0ah
DB 0dh, 0ah
DB 0dh, 0ah
DB 0dh, 0ah
DB 0dh, 0ah

        DB "$"